### ISSUE TITLE
IT_0 Jaycee Dela Cruz & Jake Perez

### ISSUE THREAD

**Issue by christianpring** [christianpring/Group-3---Event-Management-System#3]
### Book Event nav bar.
- Overview of the events.
- Images of the events that can be click to choose. (tas meron btn to confirm, then proceed sa package)
- Once the event was chosen, list of packages with the info(inclusion) of package will appear. User will choose again which event package they prefer. ( again meron btn to confirm then proceed sa calendar for scheduling)
- After they picked a package, a Calendar will appear for them to reserve a slot for their event. 
- Once done scheduling, Proceed to Payment na para matapos na 'yung booking nya.
- The transaction cannot be concluded until the down payment is done. *note: the selected schedule will still be available on the calendar unless the transaction is finished (sa database side din 'to, ayusin nalang natin after maayos lahat sa user)

**Summary:** 
_-eventOffers > eventPackage > Calendar for scheduling > payment._

**Files:**
_-bookEvent.php
-src/css/bookEvent.css_

(**add** php files for eventOffers, eventPackage, Calendar, and Payment.) & (**add** css files for the design each)
**same php file location** _dashboard/user/.._
**same css file location** _src/css/.._

**Comment by Perez-Jake** [comment]
[bookEvent.zip](https://github.com/user-attachments/files/17903779/bookEvent.zip)
